### ISSUE TITLE
This app is doesn’t available in AppStore for Russia

### ISSUE THREAD

**Issue by MrLa** [MaartenWL/rage#10]
When it will be available?

**Comment by MaartenWL** [comment]
Hi MrLA

This app is indeed no longer for sale in Russia. This is because I have had several unpleasant experiences with Russian buyers.
For some reason Russian users appeared to experiencing more problems with my app than users from other countries. More than once they were unable to explain these problems to me in understandable English. That made me decide to stop selling my app in this country. 
I'm sorry.
