### ISSUE TITLE
Touch for virus - 

### ISSUE THREAD

**Issue by StudioSilenzio** [MaartenWL/rage#2]
Hi! I just bought te app. Is it possibile that the app "asks" Virus for current sound? I Mean, I'd like to edit a patch stored in the wirus with the app. How can I "transfer" patch setings (OSC, filters etc.) into the app? The second question is about arpeggiator: is it possibile to edit patterns like using Virus Control from access or Virus HC from Mystery Islands?

**Comment by MaartenWL** [comment]
Hi, i think you also asked for this on Facebook? To be save here's my answer:
an interface for creating a custom arpeggiator pattern will be added some day, although I can't give a timeframe. I've already done some work for it, but it's not finished yet.

The functionality for receiving patches from a Virus synth is the most requested improvement at this point. I have to overcome some technical difficulties in order to make that work. The underlying software is use has a problem, maybe a bug, making it unable to read out the information which is received from the Virus synth.  Can't promise anything, but i'm looking into it.
