### ISSUE TITLE
Touch for Virus - Questions

### ISSUE THREAD

**Issue by SENFritz** [MaartenWL/rage#3]
Hi, i've downloaded your Touch for Virus app for iOS and connected my Virus TI Snow to my iPad. 
It looks very good and i like to use it a lot. A couple of questions occure when using the app.

-Are there any more patches to choose from in the apps library other than the 4 examples? 
The Access company page offers a lot of good patches for free and i'd like to use them in the app.
-Is there any way to transmit (import) patches from the Virus TI Snow hardware to the app editor?
-Is there any way to transmit (export) patches form the app to the Virus TI Snow hardware? 

Actually i thought to use your app for flipping thru the patches on the Access Virus hardware and have them sent to the app, there one could watch the settings and learn about the programming.

Thanks a lot.

 SENFritz

ADD-ON/5 minutes later:
 I did read and understand the info on the other thread about the same question (using the 
hardware patches). **There really should be some sort of import for patch data to the app.**

**Comment by MaartenWL** [comment]
Answered this by mail with the following reacting:

Some answers to your questions

The library contains only some demo patches because i’m not a guru patch designer. The app was designed to let people build their own patches, so I assumed people would not be interested in my experimental, amateur patches.
The app is meant to let you learn by doing.

When you select a patch in the app, or change some settings, these are automatically send to the synthesizer, otherwise the app would not make sense. So sending a patch from the app, to the synthesizer is the whole point of the app. That does work. Ofcourse you can save a patch on the synth itself like you would normally do without the app.

However, the other way around (sending a patch from the synthesizer towards the app) is not available (yet) because the app was designed to create sounds, not to copy them from elsewhere. that said, other users too have 
requested features to send patches towards the app. I understand this more important to other people than i expected.  
To make that work, I have to overcome a bug in underlying third-party software i’m using to deal with MIDI data.
It cannot deal with the patch dumps from the Virus TI. This is very complicated stuff (at least for me), but I am trying different ways to solve this.

So I hope to make you happy with this feature in the future.
